### ISSUE TITLE
Major tag v0 doesn't exist

### ISSUE THREAD

**Issue by gofrolist** [tfsec/tfsec-pr-commenter-action#31]
First of all I want to thank you for your useful GitHub action.
May be it's time to release v1 because pointing to v0 is quite odd.

Anyway major tag v0 doesn't exist.

Regarding to official GitHub [recommendations](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations) and [here](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management)

> Make the new release available to those binding to the major version tag: Move the major version tag (v1, v2, etc.) to point to the ref of the current release. This will act as the stable release for that major version. You should keep this tag updated to the most recent stable minor/patch release.

Because of that I can't use v0 tag and should point it to specific tag like v0.1.10
```
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v0.1.10
```
Only way I can see it right now is use main branch which is not good for production usage
```
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
```

You can use other GitHub actions like [actions-tagger](https://github.com/marketplace/actions/actions-tagger) or [update-major-minor-semver](https://github.com/marketplace/actions/update-major-minor-semver) for this purpose.

**Comment by owenrumney** [comment]
Yup, next release will be a v1

**Comment by gofrolist** [comment]
There is still missing `v1` tag only `v1.0.0` is available
