### ISSUE TITLE
tfsec not returning anything after being invoked

### ISSUE THREAD

**Issue by brandon-bailey-rc** [tfsec/tfsec-pr-commenter-action#33]
As soon as `tfsec --format=json .` is printed, the action moves directly onto the Post Clone repo workflow

![Screen Shot 2021-10-29 at 11 04 49 AM](https://user-images.githubusercontent.com/81580001/139458766-ee5eb333-4166-4ad4-8508-0a4bd4ee70a8.png)

**Comment by brandon-bailey-rc** [comment]
It appears that if I manually change the working_directory it works, but in the `.` it does not navigate to other sub folders and returns 
```
{
	"results": null
}
```

**Comment by cody-carlson** [comment]
I am experiencing the same issue on some (not all) of my repositories.  Can copy the same workflow file, and a folder that flags in a repository, over to another 'problem' repository and I see the exact same behavior you do.  No known workarounds other than 'use a different repository'

**Comment by cody-carlson** [comment]
I was actually able to find a workaround with the working_directory flag, is there a way to recursively search folders?

**Comment by breaman** [comment]
I have run into this same issue as well and have found that if I have all my terraform files at just the root level, things work ok, or if I have them all in subfolders, it works, ok, but if I have a terraform file at the root level as well as in subfolder, then things stop working for me with the behavior from the original poster.

So this layout works:
./main.tf

and this layout works:
./infrastructure/module1/main.tf

and even this layout works:
./infrastructure/module1/main.tf
./infrastructure/module2/main.tf

but having the following doesn't work:
./main.tf
./infrastructure/module1/main.tf

also having the following doesn't work:
./infrastructure/main.tf
./infrastructure/module1/main.tf

**Comment by cody-carlson** [comment]
I can confirm I've been able to replicate the situations dictated above by @breaman

**Comment by owenrumney** [comment]
Hey @cody-carlson @breaman  @brandon-bailey-rc  - I've been neglecting this project a bit - it should be way more robust with v1.0.2 

Is this issue still occurring?

Again, apologies for the tardiness :-)

**Comment by richstokes** [comment]
I think this (https://github.com/aquasecurity/tfsec-pr-commenter-action/issues/46) may be related. the tool outputs nothing in the PR and seems to be ignoring all the checks for some reason.
