### ISSUE TITLE
fail to run tf-pr-commenter

### ISSUE THREAD

**Issue by luizm** [tfsec/tfsec-pr-commenter-action#9]
First, thank you for the tfsec :)

I've tried to use these action and found some error during execution:

```
WARNING: Failed to load module: missing module with source 'cloudposse/cloudtrail-s3-bucket/aws' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'USSBA/inspector/aws' -  try to 'terraform init' first
+ echo 'tfsec errors occurred, running commenter...'
tfsec errors occurred, running commenter...
```

Is it works when tf is using modules?

**Comment by danielfm** [comment]
I'm not seeing any warnings here, but the result is the same. Looks like the same bug. I don't see the errors found by `tfsec` anywhere, and the logs don't show any useful information.

```
+ '[' -n /github/workspace ']'
+ cd /github/workspace
+ tfsec --format=json .
+ echo 'tfsec errors occurred, running commenter...'
+ commenter
tfsec errors occurred, running commenter...
Starting the github commenter...
```

**Comment by bulebuk** [comment]
@danielfm Looks like it will only generate comments if the tfsec violation is found on *modified* lines of code. Try creating a PR that introduces a new violation and see if you get a comment.

**Comment by owenrumney** [comment]
Hey @danielfm  and @luizm sorry for the delay on this, we've got a lot more time to work on tfsec now so I'm tackling this issue today

@bulebuk  is correct, the PRs are only commented on in areas where there is a violation, that said, something in the entrypoint is clearly broken

**Comment by owenrumney** [comment]
@luizm  - I'm hoping v.01.7 should give more information - the action can't run a `terraform init` on your behalf because it doesn't know which version of terraform you're using. tfsec only cares that it is hclv2 or tf.json format.

Could you run again with the latest @main action and let me know if the logs help resolve your concern?

**Comment by luizm** [comment]
> the action can't run a `terraform init` on your behalf because it doesn't know which version of terraform you're using. tfsec only cares that it is hclv2 or tf.json format.

I get, probably that is it.. I gonna try again

Thank you
